// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: optio/distribute/query.proto

package types

import (
	context "context"
	fmt "fmt"
	query "github.com/cosmos/cosmos-sdk/types/query"
	_ "github.com/cosmos/cosmos-sdk/types/tx/amino"
	_ "github.com/cosmos/gogoproto/gogoproto"
	grpc1 "github.com/cosmos/gogoproto/grpc"
	proto "github.com/cosmos/gogoproto/proto"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

// QueryParamsRequest is request type for the Query/Params RPC method.
type QueryParamsRequest struct {
}

func (m *QueryParamsRequest) Reset()         { *m = QueryParamsRequest{} }
func (m *QueryParamsRequest) String() string { return proto.CompactTextString(m) }
func (*QueryParamsRequest) ProtoMessage()    {}
func (*QueryParamsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_15c1900b129de845, []int{0}
}
func (m *QueryParamsRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryParamsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryParamsRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryParamsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryParamsRequest.Merge(m, src)
}
func (m *QueryParamsRequest) XXX_Size() int {
	return m.Size()
}
func (m *QueryParamsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryParamsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryParamsRequest proto.InternalMessageInfo

// QueryParamsResponse is response type for the Query/Params RPC method.
type QueryParamsResponse struct {
	// params holds all the parameters of this module.
	Params Params `protobuf:"bytes,1,opt,name=params,proto3" json:"params"`
}

func (m *QueryParamsResponse) Reset()         { *m = QueryParamsResponse{} }
func (m *QueryParamsResponse) String() string { return proto.CompactTextString(m) }
func (*QueryParamsResponse) ProtoMessage()    {}
func (*QueryParamsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_15c1900b129de845, []int{1}
}
func (m *QueryParamsResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryParamsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryParamsResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryParamsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryParamsResponse.Merge(m, src)
}
func (m *QueryParamsResponse) XXX_Size() int {
	return m.Size()
}
func (m *QueryParamsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryParamsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryParamsResponse proto.InternalMessageInfo

func (m *QueryParamsResponse) GetParams() Params {
	if m != nil {
		return m.Params
	}
	return Params{}
}

type QueryGetDailyDistributionTotalRequest struct {
	Date string `protobuf:"bytes,1,opt,name=date,proto3" json:"date,omitempty"`
}

func (m *QueryGetDailyDistributionTotalRequest) Reset()         { *m = QueryGetDailyDistributionTotalRequest{} }
func (m *QueryGetDailyDistributionTotalRequest) String() string { return proto.CompactTextString(m) }
func (*QueryGetDailyDistributionTotalRequest) ProtoMessage()    {}
func (*QueryGetDailyDistributionTotalRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_15c1900b129de845, []int{2}
}
func (m *QueryGetDailyDistributionTotalRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryGetDailyDistributionTotalRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryGetDailyDistributionTotalRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryGetDailyDistributionTotalRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryGetDailyDistributionTotalRequest.Merge(m, src)
}
func (m *QueryGetDailyDistributionTotalRequest) XXX_Size() int {
	return m.Size()
}
func (m *QueryGetDailyDistributionTotalRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryGetDailyDistributionTotalRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryGetDailyDistributionTotalRequest proto.InternalMessageInfo

func (m *QueryGetDailyDistributionTotalRequest) GetDate() string {
	if m != nil {
		return m.Date
	}
	return ""
}

type QueryGetDailyDistributionTotalResponse struct {
	Total uint64 `protobuf:"varint,1,opt,name=total,proto3" json:"total,omitempty"`
}

func (m *QueryGetDailyDistributionTotalResponse) Reset() {
	*m = QueryGetDailyDistributionTotalResponse{}
}
func (m *QueryGetDailyDistributionTotalResponse) String() string { return proto.CompactTextString(m) }
func (*QueryGetDailyDistributionTotalResponse) ProtoMessage()    {}
func (*QueryGetDailyDistributionTotalResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_15c1900b129de845, []int{3}
}
func (m *QueryGetDailyDistributionTotalResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryGetDailyDistributionTotalResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryGetDailyDistributionTotalResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryGetDailyDistributionTotalResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryGetDailyDistributionTotalResponse.Merge(m, src)
}
func (m *QueryGetDailyDistributionTotalResponse) XXX_Size() int {
	return m.Size()
}
func (m *QueryGetDailyDistributionTotalResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryGetDailyDistributionTotalResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryGetDailyDistributionTotalResponse proto.InternalMessageInfo

func (m *QueryGetDailyDistributionTotalResponse) GetTotal() uint64 {
	if m != nil {
		return m.Total
	}
	return 0
}

type QueryAllDailyDistributionTotalRequest struct {
	Pagination *query.PageRequest `protobuf:"bytes,1,opt,name=pagination,proto3" json:"pagination,omitempty"`
}

func (m *QueryAllDailyDistributionTotalRequest) Reset()         { *m = QueryAllDailyDistributionTotalRequest{} }
func (m *QueryAllDailyDistributionTotalRequest) String() string { return proto.CompactTextString(m) }
func (*QueryAllDailyDistributionTotalRequest) ProtoMessage()    {}
func (*QueryAllDailyDistributionTotalRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_15c1900b129de845, []int{4}
}
func (m *QueryAllDailyDistributionTotalRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryAllDailyDistributionTotalRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryAllDailyDistributionTotalRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryAllDailyDistributionTotalRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryAllDailyDistributionTotalRequest.Merge(m, src)
}
func (m *QueryAllDailyDistributionTotalRequest) XXX_Size() int {
	return m.Size()
}
func (m *QueryAllDailyDistributionTotalRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryAllDailyDistributionTotalRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryAllDailyDistributionTotalRequest proto.InternalMessageInfo

func (m *QueryAllDailyDistributionTotalRequest) GetPagination() *query.PageRequest {
	if m != nil {
		return m.Pagination
	}
	return nil
}

type QueryAllDailyDistributionTotalResponse struct {
	DailyDistributionTotals []DailyDistributionTotalEntry `protobuf:"bytes,1,rep,name=dailyDistributionTotals,proto3" json:"dailyDistributionTotals"`
	Pagination              *query.PageResponse           `protobuf:"bytes,2,opt,name=pagination,proto3" json:"pagination,omitempty"`
}

func (m *QueryAllDailyDistributionTotalResponse) Reset() {
	*m = QueryAllDailyDistributionTotalResponse{}
}
func (m *QueryAllDailyDistributionTotalResponse) String() string { return proto.CompactTextString(m) }
func (*QueryAllDailyDistributionTotalResponse) ProtoMessage()    {}
func (*QueryAllDailyDistributionTotalResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_15c1900b129de845, []int{5}
}
func (m *QueryAllDailyDistributionTotalResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryAllDailyDistributionTotalResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryAllDailyDistributionTotalResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryAllDailyDistributionTotalResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryAllDailyDistributionTotalResponse.Merge(m, src)
}
func (m *QueryAllDailyDistributionTotalResponse) XXX_Size() int {
	return m.Size()
}
func (m *QueryAllDailyDistributionTotalResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryAllDailyDistributionTotalResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryAllDailyDistributionTotalResponse proto.InternalMessageInfo

func (m *QueryAllDailyDistributionTotalResponse) GetDailyDistributionTotals() []DailyDistributionTotalEntry {
	if m != nil {
		return m.DailyDistributionTotals
	}
	return nil
}

func (m *QueryAllDailyDistributionTotalResponse) GetPagination() *query.PageResponse {
	if m != nil {
		return m.Pagination
	}
	return nil
}

type DailyDistributionTotalEntry struct {
	Date   string `protobuf:"bytes,1,opt,name=date,proto3" json:"date,omitempty"`
	Amount string `protobuf:"bytes,2,opt,name=amount,proto3" json:"amount,omitempty"`
}

func (m *DailyDistributionTotalEntry) Reset()         { *m = DailyDistributionTotalEntry{} }
func (m *DailyDistributionTotalEntry) String() string { return proto.CompactTextString(m) }
func (*DailyDistributionTotalEntry) ProtoMessage()    {}
func (*DailyDistributionTotalEntry) Descriptor() ([]byte, []int) {
	return fileDescriptor_15c1900b129de845, []int{6}
}
func (m *DailyDistributionTotalEntry) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *DailyDistributionTotalEntry) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_DailyDistributionTotalEntry.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *DailyDistributionTotalEntry) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DailyDistributionTotalEntry.Merge(m, src)
}
func (m *DailyDistributionTotalEntry) XXX_Size() int {
	return m.Size()
}
func (m *DailyDistributionTotalEntry) XXX_DiscardUnknown() {
	xxx_messageInfo_DailyDistributionTotalEntry.DiscardUnknown(m)
}

var xxx_messageInfo_DailyDistributionTotalEntry proto.InternalMessageInfo

func (m *DailyDistributionTotalEntry) GetDate() string {
	if m != nil {
		return m.Date
	}
	return ""
}

func (m *DailyDistributionTotalEntry) GetAmount() string {
	if m != nil {
		return m.Amount
	}
	return ""
}

func init() {
	proto.RegisterType((*QueryParamsRequest)(nil), "optio.distribute.QueryParamsRequest")
	proto.RegisterType((*QueryParamsResponse)(nil), "optio.distribute.QueryParamsResponse")
	proto.RegisterType((*QueryGetDailyDistributionTotalRequest)(nil), "optio.distribute.QueryGetDailyDistributionTotalRequest")
	proto.RegisterType((*QueryGetDailyDistributionTotalResponse)(nil), "optio.distribute.QueryGetDailyDistributionTotalResponse")
	proto.RegisterType((*QueryAllDailyDistributionTotalRequest)(nil), "optio.distribute.QueryAllDailyDistributionTotalRequest")
	proto.RegisterType((*QueryAllDailyDistributionTotalResponse)(nil), "optio.distribute.QueryAllDailyDistributionTotalResponse")
	proto.RegisterType((*DailyDistributionTotalEntry)(nil), "optio.distribute.DailyDistributionTotalEntry")
}

func init() { proto.RegisterFile("optio/distribute/query.proto", fileDescriptor_15c1900b129de845) }

var fileDescriptor_15c1900b129de845 = []byte{
	// 564 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x9c, 0x54, 0xcf, 0x6a, 0x13, 0x41,
	0x18, 0xcf, 0xd4, 0x34, 0xd0, 0xe9, 0x45, 0xc7, 0x50, 0x6b, 0xac, 0xab, 0x2c, 0x36, 0x86, 0x82,
	0x33, 0x24, 0x1e, 0x2c, 0x16, 0xd4, 0x84, 0x6a, 0x10, 0x0f, 0xd6, 0xd5, 0x93, 0x97, 0x32, 0x9b,
	0x0c, 0xeb, 0xc0, 0xee, 0xce, 0x76, 0x67, 0xb6, 0x18, 0xc4, 0x8b, 0xe0, 0x5d, 0xf0, 0x25, 0x3c,
	0x7a, 0xf5, 0x0d, 0x7a, 0x0c, 0xe8, 0xc1, 0x93, 0x94, 0x44, 0xf0, 0x35, 0x64, 0x67, 0x47, 0x9a,
	0x98, 0xdd, 0x2c, 0x7a, 0x09, 0xb3, 0x33, 0xdf, 0xef, 0xfb, 0xfd, 0x99, 0x6f, 0x02, 0xb7, 0x44,
	0xa4, 0xb8, 0x20, 0x43, 0x2e, 0x55, 0xcc, 0xdd, 0x44, 0x31, 0x72, 0x94, 0xb0, 0x78, 0x84, 0xa3,
	0x58, 0x28, 0x81, 0xce, 0xeb, 0x53, 0x7c, 0x76, 0xda, 0xb8, 0x40, 0x03, 0x1e, 0x0a, 0xa2, 0x7f,
	0xb3, 0xa2, 0x46, 0xdd, 0x13, 0x9e, 0xd0, 0x4b, 0x92, 0xae, 0xcc, 0xee, 0x96, 0x27, 0x84, 0xe7,
	0x33, 0x42, 0x23, 0x4e, 0x68, 0x18, 0x0a, 0x45, 0x15, 0x17, 0xa1, 0x34, 0xa7, 0x3b, 0x03, 0x21,
	0x03, 0x21, 0x89, 0x4b, 0xa5, 0x61, 0x24, 0xc7, 0x6d, 0x97, 0x29, 0xda, 0x26, 0x11, 0xf5, 0x78,
	0xa8, 0x8b, 0x4d, 0xed, 0xd5, 0x05, 0x89, 0x11, 0x8d, 0x69, 0x60, 0x5a, 0xd9, 0x75, 0x88, 0x9e,
	0xa5, 0x0d, 0x0e, 0xf4, 0xa6, 0xc3, 0x8e, 0x12, 0x26, 0x95, 0xed, 0xc0, 0x8b, 0x73, 0xbb, 0x32,
	0x12, 0xa1, 0x64, 0x68, 0x0f, 0xd6, 0x32, 0xf0, 0x26, 0xb8, 0x0e, 0x5a, 0xeb, 0x9d, 0x4d, 0xfc,
	0xb7, 0x43, 0x9c, 0x21, 0x7a, 0x6b, 0x27, 0x3f, 0xae, 0x55, 0x3e, 0xfd, 0xfa, 0xbc, 0x03, 0x1c,
	0x03, 0xb1, 0xf7, 0xe0, 0xb6, 0xee, 0xd9, 0x67, 0x6a, 0x9f, 0x72, 0x7f, 0xb4, 0xff, 0x07, 0xc4,
	0x45, 0xf8, 0x42, 0x28, 0xea, 0x1b, 0x72, 0x84, 0x60, 0x75, 0x48, 0x15, 0xd3, 0x1c, 0x6b, 0x8e,
	0x5e, 0xdb, 0xf7, 0x60, 0xb3, 0x0c, 0x6c, 0x34, 0xd6, 0xe1, 0xaa, 0x4a, 0x37, 0x34, 0xbc, 0xea,
	0x64, 0x1f, 0xb6, 0x30, 0xe4, 0x5d, 0xdf, 0x5f, 0x4e, 0xfe, 0x08, 0xc2, 0xb3, 0x08, 0x8d, 0xcd,
	0x26, 0xce, 0xf2, 0xc6, 0x69, 0xde, 0x38, 0xbb, 0x61, 0x93, 0x37, 0x3e, 0xa0, 0x1e, 0x33, 0x58,
	0x67, 0x06, 0x69, 0x9f, 0x02, 0xa3, 0x78, 0x09, 0xa3, 0x51, 0x1c, 0xc0, 0x4b, 0xc3, 0xdc, 0x8a,
	0x34, 0xe6, 0x73, 0xad, 0xf5, 0xce, 0xad, 0xc5, 0x98, 0xf3, 0x5b, 0x3e, 0x0c, 0x55, 0x3c, 0xea,
	0x55, 0xd3, 0xec, 0x9d, 0xa2, 0x9e, 0xa8, 0x3f, 0xe7, 0x70, 0x45, 0x3b, 0xbc, 0x59, 0xea, 0x30,
	0xd3, 0x3a, 0x67, 0xf1, 0x31, 0xbc, 0xb2, 0x44, 0x46, 0xde, 0x35, 0xa2, 0x0d, 0x58, 0xa3, 0x81,
	0x48, 0x42, 0xa5, 0x79, 0xd7, 0x1c, 0xf3, 0xd5, 0xf9, 0x52, 0x85, 0xab, 0x3a, 0x2d, 0xf4, 0x1e,
	0xc0, 0x5a, 0x36, 0x43, 0xe8, 0xc6, 0xa2, 0xed, 0xc5, 0x51, 0x6d, 0x6c, 0x97, 0x54, 0x65, 0xc2,
	0x6d, 0xfc, 0xee, 0xeb, 0xcf, 0x8f, 0x2b, 0x2d, 0xd4, 0x24, 0x4f, 0xd3, 0xf2, 0xe7, 0x2c, 0x3e,
	0xe6, 0x03, 0x26, 0x49, 0xc1, 0xeb, 0x40, 0xdf, 0x00, 0xdc, 0xc8, 0x77, 0x87, 0xee, 0x14, 0x30,
	0x96, 0x0d, 0x76, 0x63, 0xf7, 0xdf, 0x81, 0x46, 0x7d, 0x5f, 0xab, 0xef, 0xa2, 0xfb, 0x65, 0xea,
	0xf5, 0xa5, 0x1f, 0x0e, 0x67, 0x1a, 0x1d, 0xea, 0x07, 0x40, 0xde, 0xa4, 0xf9, 0xbf, 0x45, 0x63,
	0x00, 0x2f, 0xe7, 0x73, 0x75, 0xfd, 0x62, 0x67, 0x65, 0xaf, 0xa6, 0xd0, 0x59, 0xe9, 0xf0, 0xdb,
	0x0f, 0xb4, 0xb3, 0xbb, 0x68, 0xf7, 0x7f, 0x9d, 0xf5, 0x9e, 0x9c, 0x4c, 0x2c, 0x30, 0x9e, 0x58,
	0xe0, 0x74, 0x62, 0x81, 0x0f, 0x53, 0xab, 0x32, 0x9e, 0x5a, 0x95, 0xef, 0x53, 0xab, 0xf2, 0xb2,
	0xed, 0x71, 0xf5, 0x2a, 0x71, 0xf1, 0x40, 0x04, 0xb9, 0xdd, 0x5f, 0xcf, 0xf6, 0x57, 0xa3, 0x88,
	0x49, 0xb7, 0xa6, 0xff, 0x15, 0x6f, 0xff, 0x0e, 0x00, 0x00, 0xff, 0xff, 0xcb, 0x43, 0xe9, 0xcc,
	0xd9, 0x05, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// QueryClient is the client API for Query service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type QueryClient interface {
	// Parameters queries the parameters of the module.
	Params(ctx context.Context, in *QueryParamsRequest, opts ...grpc.CallOption) (*QueryParamsResponse, error)
	// Queries a list of DailyDistributionTotal items.
	DailyDistributionTotal(ctx context.Context, in *QueryGetDailyDistributionTotalRequest, opts ...grpc.CallOption) (*QueryGetDailyDistributionTotalResponse, error)
	DailyDistributionTotalAll(ctx context.Context, in *QueryAllDailyDistributionTotalRequest, opts ...grpc.CallOption) (*QueryAllDailyDistributionTotalResponse, error)
}

type queryClient struct {
	cc grpc1.ClientConn
}

func NewQueryClient(cc grpc1.ClientConn) QueryClient {
	return &queryClient{cc}
}

func (c *queryClient) Params(ctx context.Context, in *QueryParamsRequest, opts ...grpc.CallOption) (*QueryParamsResponse, error) {
	out := new(QueryParamsResponse)
	err := c.cc.Invoke(ctx, "/optio.distribute.Query/Params", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) DailyDistributionTotal(ctx context.Context, in *QueryGetDailyDistributionTotalRequest, opts ...grpc.CallOption) (*QueryGetDailyDistributionTotalResponse, error) {
	out := new(QueryGetDailyDistributionTotalResponse)
	err := c.cc.Invoke(ctx, "/optio.distribute.Query/DailyDistributionTotal", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) DailyDistributionTotalAll(ctx context.Context, in *QueryAllDailyDistributionTotalRequest, opts ...grpc.CallOption) (*QueryAllDailyDistributionTotalResponse, error) {
	out := new(QueryAllDailyDistributionTotalResponse)
	err := c.cc.Invoke(ctx, "/optio.distribute.Query/DailyDistributionTotalAll", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// QueryServer is the server API for Query service.
type QueryServer interface {
	// Parameters queries the parameters of the module.
	Params(context.Context, *QueryParamsRequest) (*QueryParamsResponse, error)
	// Queries a list of DailyDistributionTotal items.
	DailyDistributionTotal(context.Context, *QueryGetDailyDistributionTotalRequest) (*QueryGetDailyDistributionTotalResponse, error)
	DailyDistributionTotalAll(context.Context, *QueryAllDailyDistributionTotalRequest) (*QueryAllDailyDistributionTotalResponse, error)
}

// UnimplementedQueryServer can be embedded to have forward compatible implementations.
type UnimplementedQueryServer struct {
}

func (*UnimplementedQueryServer) Params(ctx context.Context, req *QueryParamsRequest) (*QueryParamsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Params not implemented")
}
func (*UnimplementedQueryServer) DailyDistributionTotal(ctx context.Context, req *QueryGetDailyDistributionTotalRequest) (*QueryGetDailyDistributionTotalResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DailyDistributionTotal not implemented")
}
func (*UnimplementedQueryServer) DailyDistributionTotalAll(ctx context.Context, req *QueryAllDailyDistributionTotalRequest) (*QueryAllDailyDistributionTotalResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DailyDistributionTotalAll not implemented")
}

func RegisterQueryServer(s grpc1.Server, srv QueryServer) {
	s.RegisterService(&_Query_serviceDesc, srv)
}

func _Query_Params_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryParamsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).Params(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/optio.distribute.Query/Params",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).Params(ctx, req.(*QueryParamsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_DailyDistributionTotal_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryGetDailyDistributionTotalRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).DailyDistributionTotal(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/optio.distribute.Query/DailyDistributionTotal",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).DailyDistributionTotal(ctx, req.(*QueryGetDailyDistributionTotalRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_DailyDistributionTotalAll_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryAllDailyDistributionTotalRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).DailyDistributionTotalAll(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/optio.distribute.Query/DailyDistributionTotalAll",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).DailyDistributionTotalAll(ctx, req.(*QueryAllDailyDistributionTotalRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var Query_serviceDesc = _Query_serviceDesc
var _Query_serviceDesc = grpc.ServiceDesc{
	ServiceName: "optio.distribute.Query",
	HandlerType: (*QueryServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Params",
			Handler:    _Query_Params_Handler,
		},
		{
			MethodName: "DailyDistributionTotal",
			Handler:    _Query_DailyDistributionTotal_Handler,
		},
		{
			MethodName: "DailyDistributionTotalAll",
			Handler:    _Query_DailyDistributionTotalAll_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "optio/distribute/query.proto",
}

func (m *QueryParamsRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryParamsRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryParamsRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	return len(dAtA) - i, nil
}

func (m *QueryParamsResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryParamsResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryParamsResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	{
		size, err := m.Params.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintQuery(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0xa
	return len(dAtA) - i, nil
}

func (m *QueryGetDailyDistributionTotalRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryGetDailyDistributionTotalRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryGetDailyDistributionTotalRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Date) > 0 {
		i -= len(m.Date)
		copy(dAtA[i:], m.Date)
		i = encodeVarintQuery(dAtA, i, uint64(len(m.Date)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *QueryGetDailyDistributionTotalResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryGetDailyDistributionTotalResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryGetDailyDistributionTotalResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Total != 0 {
		i = encodeVarintQuery(dAtA, i, uint64(m.Total))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func (m *QueryAllDailyDistributionTotalRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryAllDailyDistributionTotalRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryAllDailyDistributionTotalRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Pagination != nil {
		{
			size, err := m.Pagination.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintQuery(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *QueryAllDailyDistributionTotalResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryAllDailyDistributionTotalResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryAllDailyDistributionTotalResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Pagination != nil {
		{
			size, err := m.Pagination.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintQuery(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x12
	}
	if len(m.DailyDistributionTotals) > 0 {
		for iNdEx := len(m.DailyDistributionTotals) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.DailyDistributionTotals[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintQuery(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0xa
		}
	}
	return len(dAtA) - i, nil
}

func (m *DailyDistributionTotalEntry) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *DailyDistributionTotalEntry) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *DailyDistributionTotalEntry) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Amount) > 0 {
		i -= len(m.Amount)
		copy(dAtA[i:], m.Amount)
		i = encodeVarintQuery(dAtA, i, uint64(len(m.Amount)))
		i--
		dAtA[i] = 0x12
	}
	if len(m.Date) > 0 {
		i -= len(m.Date)
		copy(dAtA[i:], m.Date)
		i = encodeVarintQuery(dAtA, i, uint64(len(m.Date)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func encodeVarintQuery(dAtA []byte, offset int, v uint64) int {
	offset -= sovQuery(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *QueryParamsRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	return n
}

func (m *QueryParamsResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = m.Params.Size()
	n += 1 + l + sovQuery(uint64(l))
	return n
}

func (m *QueryGetDailyDistributionTotalRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Date)
	if l > 0 {
		n += 1 + l + sovQuery(uint64(l))
	}
	return n
}

func (m *QueryGetDailyDistributionTotalResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Total != 0 {
		n += 1 + sovQuery(uint64(m.Total))
	}
	return n
}

func (m *QueryAllDailyDistributionTotalRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Pagination != nil {
		l = m.Pagination.Size()
		n += 1 + l + sovQuery(uint64(l))
	}
	return n
}

func (m *QueryAllDailyDistributionTotalResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if len(m.DailyDistributionTotals) > 0 {
		for _, e := range m.DailyDistributionTotals {
			l = e.Size()
			n += 1 + l + sovQuery(uint64(l))
		}
	}
	if m.Pagination != nil {
		l = m.Pagination.Size()
		n += 1 + l + sovQuery(uint64(l))
	}
	return n
}

func (m *DailyDistributionTotalEntry) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Date)
	if l > 0 {
		n += 1 + l + sovQuery(uint64(l))
	}
	l = len(m.Amount)
	if l > 0 {
		n += 1 + l + sovQuery(uint64(l))
	}
	return n
}

func sovQuery(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozQuery(x uint64) (n int) {
	return sovQuery(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *QueryParamsRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryParamsRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryParamsRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryParamsResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryParamsResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryParamsResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Params", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.Params.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryGetDailyDistributionTotalRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryGetDailyDistributionTotalRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryGetDailyDistributionTotalRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Date", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Date = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryGetDailyDistributionTotalResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryGetDailyDistributionTotalResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryGetDailyDistributionTotalResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Total", wireType)
			}
			m.Total = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Total |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryAllDailyDistributionTotalRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryAllDailyDistributionTotalRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryAllDailyDistributionTotalRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Pagination", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Pagination == nil {
				m.Pagination = &query.PageRequest{}
			}
			if err := m.Pagination.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryAllDailyDistributionTotalResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryAllDailyDistributionTotalResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryAllDailyDistributionTotalResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field DailyDistributionTotals", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.DailyDistributionTotals = append(m.DailyDistributionTotals, DailyDistributionTotalEntry{})
			if err := m.DailyDistributionTotals[len(m.DailyDistributionTotals)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Pagination", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Pagination == nil {
				m.Pagination = &query.PageResponse{}
			}
			if err := m.Pagination.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *DailyDistributionTotalEntry) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: DailyDistributionTotalEntry: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: DailyDistributionTotalEntry: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Date", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Date = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Amount", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Amount = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipQuery(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthQuery
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupQuery
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthQuery
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthQuery        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowQuery          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupQuery = fmt.Errorf("proto: unexpected end of group")
)
