// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             (unknown)
// source: optio/distro/query.proto

package distro

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	Query_Params_FullMethodName                    = "/optio.distro.Query/Params"
	Query_DailyDistributionTotal_FullMethodName    = "/optio.distro.Query/DailyDistributionTotal"
	Query_DailyDistributionTotalAll_FullMethodName = "/optio.distro.Query/DailyDistributionTotalAll"
)

// QueryClient is the client API for Query service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type QueryClient interface {
	// Parameters queries the parameters of the module.
	Params(ctx context.Context, in *QueryParamsRequest, opts ...grpc.CallOption) (*QueryParamsResponse, error)
	// Queries a list of DailyDistributionTotal items.
	DailyDistributionTotal(ctx context.Context, in *QueryGetDailyDistributionTotalRequest, opts ...grpc.CallOption) (*QueryGetDailyDistributionTotalResponse, error)
	DailyDistributionTotalAll(ctx context.Context, in *QueryAllDailyDistributionTotalRequest, opts ...grpc.CallOption) (*QueryAllDailyDistributionTotalResponse, error)
}

type queryClient struct {
	cc grpc.ClientConnInterface
}

func NewQueryClient(cc grpc.ClientConnInterface) QueryClient {
	return &queryClient{cc}
}

func (c *queryClient) Params(ctx context.Context, in *QueryParamsRequest, opts ...grpc.CallOption) (*QueryParamsResponse, error) {
	out := new(QueryParamsResponse)
	err := c.cc.Invoke(ctx, Query_Params_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) DailyDistributionTotal(ctx context.Context, in *QueryGetDailyDistributionTotalRequest, opts ...grpc.CallOption) (*QueryGetDailyDistributionTotalResponse, error) {
	out := new(QueryGetDailyDistributionTotalResponse)
	err := c.cc.Invoke(ctx, Query_DailyDistributionTotal_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) DailyDistributionTotalAll(ctx context.Context, in *QueryAllDailyDistributionTotalRequest, opts ...grpc.CallOption) (*QueryAllDailyDistributionTotalResponse, error) {
	out := new(QueryAllDailyDistributionTotalResponse)
	err := c.cc.Invoke(ctx, Query_DailyDistributionTotalAll_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// QueryServer is the server API for Query service.
// All implementations must embed UnimplementedQueryServer
// for forward compatibility
type QueryServer interface {
	// Parameters queries the parameters of the module.
	Params(context.Context, *QueryParamsRequest) (*QueryParamsResponse, error)
	// Queries a list of DailyDistributionTotal items.
	DailyDistributionTotal(context.Context, *QueryGetDailyDistributionTotalRequest) (*QueryGetDailyDistributionTotalResponse, error)
	DailyDistributionTotalAll(context.Context, *QueryAllDailyDistributionTotalRequest) (*QueryAllDailyDistributionTotalResponse, error)
	mustEmbedUnimplementedQueryServer()
}

// UnimplementedQueryServer must be embedded to have forward compatible implementations.
type UnimplementedQueryServer struct {
}

func (UnimplementedQueryServer) Params(context.Context, *QueryParamsRequest) (*QueryParamsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Params not implemented")
}
func (UnimplementedQueryServer) DailyDistributionTotal(context.Context, *QueryGetDailyDistributionTotalRequest) (*QueryGetDailyDistributionTotalResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DailyDistributionTotal not implemented")
}
func (UnimplementedQueryServer) DailyDistributionTotalAll(context.Context, *QueryAllDailyDistributionTotalRequest) (*QueryAllDailyDistributionTotalResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DailyDistributionTotalAll not implemented")
}
func (UnimplementedQueryServer) mustEmbedUnimplementedQueryServer() {}

// UnsafeQueryServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to QueryServer will
// result in compilation errors.
type UnsafeQueryServer interface {
	mustEmbedUnimplementedQueryServer()
}

func RegisterQueryServer(s grpc.ServiceRegistrar, srv QueryServer) {
	s.RegisterService(&Query_ServiceDesc, srv)
}

func _Query_Params_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryParamsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).Params(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Query_Params_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).Params(ctx, req.(*QueryParamsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_DailyDistributionTotal_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryGetDailyDistributionTotalRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).DailyDistributionTotal(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Query_DailyDistributionTotal_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).DailyDistributionTotal(ctx, req.(*QueryGetDailyDistributionTotalRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_DailyDistributionTotalAll_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryAllDailyDistributionTotalRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).DailyDistributionTotalAll(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Query_DailyDistributionTotalAll_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).DailyDistributionTotalAll(ctx, req.(*QueryAllDailyDistributionTotalRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Query_ServiceDesc is the grpc.ServiceDesc for Query service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Query_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "optio.distro.Query",
	HandlerType: (*QueryServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Params",
			Handler:    _Query_Params_Handler,
		},
		{
			MethodName: "DailyDistributionTotal",
			Handler:    _Query_DailyDistributionTotal_Handler,
		},
		{
			MethodName: "DailyDistributionTotalAll",
			Handler:    _Query_DailyDistributionTotalAll_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "optio/distro/query.proto",
}
