// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: optio/distro/params.proto

package types

import (
	fmt "fmt"
	_ "github.com/cosmos/cosmos-sdk/types/tx/amino"
	_ "github.com/cosmos/gogoproto/gogoproto"
	proto "github.com/cosmos/gogoproto/proto"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

// Params defines the parameters for the module.
type Params struct {
	AuthorizedAccounts          []string `protobuf:"bytes,1,rep,name=authorizedAccounts,proto3" json:"authorizedAccounts,omitempty" yaml:"authorized_accounts"`
	Denom                       string   `protobuf:"bytes,2,opt,name=denom,proto3" json:"denom,omitempty" yaml:"denom"`
	MaxSupply                   uint64   `protobuf:"varint,3,opt,name=maxSupply,proto3" json:"maxSupply,omitempty" yaml:"max_supply"`
	DistributionStartDate       string   `protobuf:"bytes,4,opt,name=distributionStartDate,proto3" json:"distributionStartDate,omitempty" yaml:"distribution_start_date"`
	MonthsInHalvingPeriod       uint64   `protobuf:"varint,5,opt,name=monthsInHalvingPeriod,proto3" json:"monthsInHalvingPeriod,omitempty" yaml:"months_in_halving_period"`
	DistributionSignerPublicKey string   `protobuf:"bytes,6,opt,name=distributionSignerPublicKey,proto3" json:"distributionSignerPublicKey,omitempty" yaml:"distribution_signer_public_key"`
}

func (m *Params) Reset()         { *m = Params{} }
func (m *Params) String() string { return proto.CompactTextString(m) }
func (*Params) ProtoMessage()    {}
func (*Params) Descriptor() ([]byte, []int) {
	return fileDescriptor_a039eced5b73dc70, []int{0}
}
func (m *Params) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *Params) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_Params.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *Params) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Params.Merge(m, src)
}
func (m *Params) XXX_Size() int {
	return m.Size()
}
func (m *Params) XXX_DiscardUnknown() {
	xxx_messageInfo_Params.DiscardUnknown(m)
}

var xxx_messageInfo_Params proto.InternalMessageInfo

func (m *Params) GetAuthorizedAccounts() []string {
	if m != nil {
		return m.AuthorizedAccounts
	}
	return nil
}

func (m *Params) GetDenom() string {
	if m != nil {
		return m.Denom
	}
	return ""
}

func (m *Params) GetMaxSupply() uint64 {
	if m != nil {
		return m.MaxSupply
	}
	return 0
}

func (m *Params) GetDistributionStartDate() string {
	if m != nil {
		return m.DistributionStartDate
	}
	return ""
}

func (m *Params) GetMonthsInHalvingPeriod() uint64 {
	if m != nil {
		return m.MonthsInHalvingPeriod
	}
	return 0
}

func (m *Params) GetDistributionSignerPublicKey() string {
	if m != nil {
		return m.DistributionSignerPublicKey
	}
	return ""
}

func init() {
	proto.RegisterType((*Params)(nil), "optio.distro.Params")
}

func init() { proto.RegisterFile("optio/distro/params.proto", fileDescriptor_a039eced5b73dc70) }

var fileDescriptor_a039eced5b73dc70 = []byte{
	// 429 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x7c, 0x92, 0x3f, 0x8b, 0x13, 0x41,
	0x18, 0xc6, 0xb3, 0xe6, 0x2e, 0x90, 0xe5, 0x0a, 0x6f, 0x30, 0xb0, 0x46, 0x98, 0x09, 0x23, 0x4a,
	0x14, 0xcc, 0x16, 0xd7, 0x5d, 0x67, 0x10, 0x54, 0x04, 0x0d, 0x9b, 0x46, 0x6d, 0x86, 0xc9, 0xee,
	0xb0, 0x19, 0x2e, 0xf3, 0x87, 0x99, 0xd9, 0x23, 0xeb, 0x47, 0xb0, 0xf2, 0x23, 0xf8, 0x11, 0xfc,
	0x18, 0x96, 0x57, 0x5a, 0x2d, 0x92, 0x14, 0x5a, 0x6f, 0x63, 0x2b, 0x99, 0x89, 0x9c, 0x4a, 0xb8,
	0x66, 0x79, 0x79, 0x9f, 0xdf, 0xfb, 0xbc, 0xcf, 0x32, 0x6f, 0x7c, 0x57, 0x69, 0xc7, 0x55, 0x5a,
	0x70, 0xeb, 0x8c, 0x4a, 0x35, 0x35, 0x54, 0xd8, 0x89, 0x36, 0xca, 0x29, 0x70, 0xe2, 0xa5, 0x49,
	0x90, 0x86, 0xa7, 0x54, 0x70, 0xa9, 0x52, 0xff, 0x0d, 0xc0, 0xf0, 0x4e, 0xa9, 0x4a, 0xe5, 0xcb,
	0x74, 0x57, 0x85, 0x2e, 0xfe, 0xd5, 0x8d, 0x7b, 0x33, 0xef, 0x03, 0x5e, 0xc7, 0x80, 0x56, 0x6e,
	0xa9, 0x0c, 0xff, 0xc0, 0x8a, 0xa7, 0x79, 0xae, 0x2a, 0xe9, 0x6c, 0x12, 0x8d, 0xba, 0xe3, 0xfe,
	0x14, 0xb6, 0x0d, 0x1a, 0xd6, 0x54, 0xac, 0xce, 0xf1, 0x35, 0x43, 0xe8, 0x1e, 0xc2, 0xd9, 0x81,
	0x49, 0xf0, 0x30, 0x3e, 0x2e, 0x98, 0x54, 0x22, 0xb9, 0x35, 0x8a, 0xc6, 0xfd, 0xe9, 0xed, 0xb6,
	0x41, 0x27, 0xc1, 0xc2, 0xb7, 0x71, 0x16, 0x64, 0x70, 0x16, 0xf7, 0x05, 0x5d, 0xcf, 0x2b, 0xad,
	0x57, 0x75, 0xd2, 0x1d, 0x45, 0xe3, 0xa3, 0xe9, 0xa0, 0x6d, 0xd0, 0x69, 0x60, 0x05, 0x5d, 0x13,
	0xeb, 0x35, 0x9c, 0x5d, 0x73, 0xe0, 0x6d, 0x3c, 0xf0, 0xbf, 0xca, 0x17, 0x95, 0xe3, 0x4a, 0xce,
	0x1d, 0x35, 0xee, 0x19, 0x75, 0x2c, 0x39, 0xf2, 0xcb, 0x70, 0xdb, 0x20, 0xb8, 0x5f, 0xf6, 0x17,
	0x46, 0xec, 0x8e, 0x23, 0x05, 0x75, 0x0c, 0x67, 0x87, 0x0d, 0xc0, 0xbb, 0x78, 0x20, 0x94, 0x74,
	0x4b, 0xfb, 0x52, 0xbe, 0xa0, 0xab, 0x4b, 0x2e, 0xcb, 0x19, 0x33, 0x5c, 0x15, 0xc9, 0xb1, 0x8f,
	0x76, 0xbf, 0x6d, 0x10, 0xda, 0x47, 0xf3, 0x18, 0xe1, 0x92, 0x2c, 0x03, 0x48, 0xb4, 0x27, 0x71,
	0x76, 0xd8, 0x01, 0x5c, 0xc4, 0xf7, 0xfe, 0xd9, 0xc9, 0x4b, 0xc9, 0xcc, 0xac, 0x5a, 0xac, 0x78,
	0xfe, 0x8a, 0xd5, 0x49, 0xcf, 0x47, 0x7f, 0xd4, 0x36, 0xe8, 0xc1, 0xa1, 0xe8, 0x9e, 0x26, 0xda,
	0xe3, 0xe4, 0x82, 0xd5, 0x38, 0xbb, 0xc9, 0xed, 0x1c, 0xfe, 0xfc, 0x8c, 0xa2, 0x8f, 0x3f, 0xbe,
	0x3c, 0x1e, 0x84, 0xa3, 0x59, 0xff, 0x39, 0x9b, 0xf0, 0xdc, 0xd3, 0xe7, 0x5f, 0x37, 0x30, 0xba,
	0xda, 0xc0, 0xe8, 0xfb, 0x06, 0x46, 0x9f, 0xb6, 0xb0, 0x73, 0xb5, 0x85, 0x9d, 0x6f, 0x5b, 0xd8,
	0x79, 0xff, 0xa4, 0xe4, 0x6e, 0x59, 0x2d, 0x26, 0xb9, 0x12, 0xe9, 0x9b, 0xdd, 0xec, 0x9c, 0x99,
	0x4b, 0x9e, 0x33, 0x9b, 0xfe, 0xe7, 0xe4, 0x6a, 0xcd, 0xec, 0xa2, 0xe7, 0x2f, 0xe9, 0xec, 0x77,
	0x00, 0x00, 0x00, 0xff, 0xff, 0x23, 0x8c, 0x88, 0x30, 0x9d, 0x02, 0x00, 0x00,
}

func (this *Params) Equal(that interface{}) bool {
	if that == nil {
		return this == nil
	}

	that1, ok := that.(*Params)
	if !ok {
		that2, ok := that.(Params)
		if ok {
			that1 = &that2
		} else {
			return false
		}
	}
	if that1 == nil {
		return this == nil
	} else if this == nil {
		return false
	}
	if len(this.AuthorizedAccounts) != len(that1.AuthorizedAccounts) {
		return false
	}
	for i := range this.AuthorizedAccounts {
		if this.AuthorizedAccounts[i] != that1.AuthorizedAccounts[i] {
			return false
		}
	}
	if this.Denom != that1.Denom {
		return false
	}
	if this.MaxSupply != that1.MaxSupply {
		return false
	}
	if this.DistributionStartDate != that1.DistributionStartDate {
		return false
	}
	if this.MonthsInHalvingPeriod != that1.MonthsInHalvingPeriod {
		return false
	}
	if this.DistributionSignerPublicKey != that1.DistributionSignerPublicKey {
		return false
	}
	return true
}
func (m *Params) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *Params) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *Params) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.DistributionSignerPublicKey) > 0 {
		i -= len(m.DistributionSignerPublicKey)
		copy(dAtA[i:], m.DistributionSignerPublicKey)
		i = encodeVarintParams(dAtA, i, uint64(len(m.DistributionSignerPublicKey)))
		i--
		dAtA[i] = 0x32
	}
	if m.MonthsInHalvingPeriod != 0 {
		i = encodeVarintParams(dAtA, i, uint64(m.MonthsInHalvingPeriod))
		i--
		dAtA[i] = 0x28
	}
	if len(m.DistributionStartDate) > 0 {
		i -= len(m.DistributionStartDate)
		copy(dAtA[i:], m.DistributionStartDate)
		i = encodeVarintParams(dAtA, i, uint64(len(m.DistributionStartDate)))
		i--
		dAtA[i] = 0x22
	}
	if m.MaxSupply != 0 {
		i = encodeVarintParams(dAtA, i, uint64(m.MaxSupply))
		i--
		dAtA[i] = 0x18
	}
	if len(m.Denom) > 0 {
		i -= len(m.Denom)
		copy(dAtA[i:], m.Denom)
		i = encodeVarintParams(dAtA, i, uint64(len(m.Denom)))
		i--
		dAtA[i] = 0x12
	}
	if len(m.AuthorizedAccounts) > 0 {
		for iNdEx := len(m.AuthorizedAccounts) - 1; iNdEx >= 0; iNdEx-- {
			i -= len(m.AuthorizedAccounts[iNdEx])
			copy(dAtA[i:], m.AuthorizedAccounts[iNdEx])
			i = encodeVarintParams(dAtA, i, uint64(len(m.AuthorizedAccounts[iNdEx])))
			i--
			dAtA[i] = 0xa
		}
	}
	return len(dAtA) - i, nil
}

func encodeVarintParams(dAtA []byte, offset int, v uint64) int {
	offset -= sovParams(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *Params) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if len(m.AuthorizedAccounts) > 0 {
		for _, s := range m.AuthorizedAccounts {
			l = len(s)
			n += 1 + l + sovParams(uint64(l))
		}
	}
	l = len(m.Denom)
	if l > 0 {
		n += 1 + l + sovParams(uint64(l))
	}
	if m.MaxSupply != 0 {
		n += 1 + sovParams(uint64(m.MaxSupply))
	}
	l = len(m.DistributionStartDate)
	if l > 0 {
		n += 1 + l + sovParams(uint64(l))
	}
	if m.MonthsInHalvingPeriod != 0 {
		n += 1 + sovParams(uint64(m.MonthsInHalvingPeriod))
	}
	l = len(m.DistributionSignerPublicKey)
	if l > 0 {
		n += 1 + l + sovParams(uint64(l))
	}
	return n
}

func sovParams(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozParams(x uint64) (n int) {
	return sovParams(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *Params) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowParams
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: Params: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: Params: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field AuthorizedAccounts", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthParams
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthParams
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.AuthorizedAccounts = append(m.AuthorizedAccounts, string(dAtA[iNdEx:postIndex]))
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Denom", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthParams
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthParams
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Denom = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field MaxSupply", wireType)
			}
			m.MaxSupply = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.MaxSupply |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field DistributionStartDate", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthParams
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthParams
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.DistributionStartDate = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 5:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field MonthsInHalvingPeriod", wireType)
			}
			m.MonthsInHalvingPeriod = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.MonthsInHalvingPeriod |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 6:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field DistributionSignerPublicKey", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthParams
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthParams
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.DistributionSignerPublicKey = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipParams(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthParams
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipParams(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowParams
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowParams
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowParams
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthParams
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupParams
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthParams
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthParams        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowParams          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupParams = fmt.Errorf("proto: unexpected end of group")
)
